/* eslint-disable @typescript-eslint/no-explicit-any */
import { cache } from 'react';
import type { Metadata } from 'next';
import { getClient, isContentTypeRegistered } from '@optimizely/cms-sdk';
import { OptimizelyComponent } from '@optimizely/cms-sdk/react/server';
import { notFound } from 'next/navigation';
import React from 'react';
import { getSiteSettings, buildContentMetadata, type PageSeo } from '@/lib/seo';

// Fetch a path's content once per request; generateMetadata + the page share it.
const getByPath = cache((path: string) => getClient().getContentByPath(path));

// Config / data content types that must NEVER be served as a public page (no URL,
// not indexable) — e.g. the Site Settings singleton. They live in the tree for
// authoring but the router treats their paths as 404. See docs/CONTENT-ARCHITECTURE.md §4.
const NON_ROUTABLE_TYPES = new Set(['SiteSettings']);
const isNonRoutable = (types: string[] = []) => types.some((t) => NON_ROUTABLE_TYPES.has(t));

/**
 * Controls what happens when a user visits a path that is not generated by `generateStaticParams`
 * See: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamicparams
 */
export const dynamicParams = true;

function removeSlashes(str: string) {
  const str2 = str.startsWith('/') ? str.slice(1) : str;

  return str2.endsWith('/') ? str2.slice(0, -1) : str2;
}

/**
 * Generates static routes at build-time
 * See: https://nextjs.org/docs/app/api-reference/functions/generate-static-params
 */
export async function generateStaticParams() {
  if (!process.env.APPLICATION_HOST) {
    return [];
  }

  // Note: in this sample site, we do not use pagination for querying pages.
  // If a website has more than 100 pages, only 100 will be statically generated
  const query = `
  query GetPosts {
    _Page(limit: 100) {
      items {
        _metadata {
          types
          url {
            base
            default
          }
        }
      }
    }
  }
    `;

  const client = getClient();
  const data = await client.request(query, {});

  return data._Page.items
    .filter((item: any) => {
      if (item?._metadata?.url?.base !== process.env.APPLICATION_HOST) {
        return false;
      }

      const contentType = item?._metadata?.types?.[0];
      if (!contentType) {
        return false;
      }

      // Never expose config/data types (e.g. Site Settings) as public pages.
      if (isNonRoutable(item?._metadata?.types)) {
        return false;
      }

      const isRegistered = isContentTypeRegistered(contentType);
      return isRegistered;
    })
    .map((item: any) => item?._metadata?.url?.default)
    .filter((path?: string) => typeof path === 'string')
    .map(removeSlashes)
    .filter((path: string) => path !== '')
    .map(
      // Format as required in Next.js
      (path: string) => ({
        slug: path.split('/'),
      }),
    );
}

type Props = {
  params: Promise<{
    slug: string[];
  }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const [content, settings] = await Promise.all([
    getByPath(`/${slug.join('/')}/`),
    getSiteSettings(),
  ]);
  const node = content[0] as
    | (PageSeo & { name?: string; _metadata?: { displayName?: string; types?: string[] } })
    | undefined;
  if (!node || isNonRoutable(node._metadata?.types)) return {};
  const fallback = node.name ?? node._metadata?.displayName ?? 'This is Dubai';
  return buildContentMetadata(node, settings, fallback);
}

export default async function Page({ params }: Props) {
  const { slug } = await params;
  const content = await getByPath(`/${slug.join('/')}/`);

  const node = content[0] as { _metadata?: { types?: string[] } } | undefined;
  // 404 for missing paths AND for config/data types that must not be public pages.
  if (!node || isNonRoutable(node._metadata?.types)) {
    notFound();
  }

  return <OptimizelyComponent content={content[0]} />;
}
