/* eslint-disable @typescript-eslint/no-explicit-any */
import { cache } from 'react';
import type { Metadata } from 'next';
import { getClient, isContentTypeRegistered } from '@optimizely/cms-sdk';
import { OptimizelyComponent } from '@optimizely/cms-sdk/react/server';
import { notFound } from 'next/navigation';
import React from 'react';
import { getSiteSettings, buildContentMetadata, type PageSeo } from '@/lib/seo';

// Fetch a path's content once per request; generateMetadata + the page share it.
const getByPath = cache((path: string) => getClient().getContentByPath(path));

/**
 * Controls what happens when a user visits a path that is not generated by `generateStaticParams`
 * See: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamicparams
 */
export const dynamicParams = true;

function removeSlashes(str: string) {
  const str2 = str.startsWith('/') ? str.slice(1) : str;

  return str2.endsWith('/') ? str2.slice(0, -1) : str2;
}

/**
 * Generates static routes at build-time
 * See: https://nextjs.org/docs/app/api-reference/functions/generate-static-params
 */
export async function generateStaticParams() {
  if (!process.env.APPLICATION_HOST) {
    return [];
  }

  // Note: in this sample site, we do not use pagination for querying pages.
  // If a website has more than 100 pages, only 100 will be statically generated
  const query = `
  query GetPosts {
    _Page(limit: 100) {
      items {
        _metadata {
          types
          url {
            base
            default
          }
        }
      }
    }
  }
    `;

  const client = getClient();
  const data = await client.request(query, {});

  return data._Page.items
    .filter((item: any) => {
      if (item?._metadata?.url?.base !== process.env.APPLICATION_HOST) {
        return false;
      }

      const contentType = item?._metadata?.types?.[0];
      if (!contentType) {
        return false;
      }

      const isRegistered = isContentTypeRegistered(contentType);
      return isRegistered;
    })
    .map((item: any) => item?._metadata?.url?.default)
    .filter((path?: string) => typeof path === 'string')
    .map(removeSlashes)
    .filter((path: string) => path !== '')
    .map(
      // Format as required in Next.js
      (path: string) => ({
        slug: path.split('/'),
      }),
    );
}

type Props = {
  params: Promise<{
    slug: string[];
  }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const [content, settings] = await Promise.all([
    getByPath(`/${slug.join('/')}/`),
    getSiteSettings(),
  ]);
  const node = content[0] as (PageSeo & { name?: string; _metadata?: { displayName?: string } }) | undefined;
  if (!node) return {};
  const fallback = node.name ?? node._metadata?.displayName ?? 'Visit Dubai';
  return buildContentMetadata(node, settings, fallback);
}

export default async function Page({ params }: Props) {
  const { slug } = await params;
  const content = await getByPath(`/${slug.join('/')}/`);

  if (content.length === 0) {
    notFound();
  }

  return <OptimizelyComponent content={content[0]} />;
}
